// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockKCPHelper creates a new instance of MockKCPHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKCPHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKCPHelper {
	mock := &MockKCPHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKCPHelper is an autogenerated mock type for the KCPHelper type
type MockKCPHelper struct {
	mock.Mock
}

type MockKCPHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKCPHelper) EXPECT() *MockKCPHelper_Expecter {
	return &MockKCPHelper_Expecter{mock: &_m.Mock}
}

// GetAllClient provides a mock function for the type MockKCPHelper
func (_mock *MockKCPHelper) GetAllClient(ctx context.Context, apiexportEndpointSliceName string) (client.Client, error) {
	ret := _mock.Called(ctx, apiexportEndpointSliceName)

	if len(ret) == 0 {
		panic("no return value specified for GetAllClient")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Client, error)); ok {
		return returnFunc(ctx, apiexportEndpointSliceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Client); ok {
		r0 = returnFunc(ctx, apiexportEndpointSliceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiexportEndpointSliceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKCPHelper_GetAllClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllClient'
type MockKCPHelper_GetAllClient_Call struct {
	*mock.Call
}

// GetAllClient is a helper method to define mock.On call
//   - ctx context.Context
//   - apiexportEndpointSliceName string
func (_e *MockKCPHelper_Expecter) GetAllClient(ctx interface{}, apiexportEndpointSliceName interface{}) *MockKCPHelper_GetAllClient_Call {
	return &MockKCPHelper_GetAllClient_Call{Call: _e.mock.On("GetAllClient", ctx, apiexportEndpointSliceName)}
}

func (_c *MockKCPHelper_GetAllClient_Call) Run(run func(ctx context.Context, apiexportEndpointSliceName string)) *MockKCPHelper_GetAllClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKCPHelper_GetAllClient_Call) Return(client1 client.Client, err error) *MockKCPHelper_GetAllClient_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *MockKCPHelper_GetAllClient_Call) RunAndReturn(run func(ctx context.Context, apiexportEndpointSliceName string) (client.Client, error)) *MockKCPHelper_GetAllClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientForLogicalCluster provides a mock function for the type MockKCPHelper
func (_mock *MockKCPHelper) NewClientForLogicalCluster(ctx context.Context, cluster string) (client.Client, error) {
	ret := _mock.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for NewClientForLogicalCluster")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Client, error)); ok {
		return returnFunc(ctx, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Client); ok {
		r0 = returnFunc(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKCPHelper_NewClientForLogicalCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClientForLogicalCluster'
type MockKCPHelper_NewClientForLogicalCluster_Call struct {
	*mock.Call
}

// NewClientForLogicalCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster string
func (_e *MockKCPHelper_Expecter) NewClientForLogicalCluster(ctx interface{}, cluster interface{}) *MockKCPHelper_NewClientForLogicalCluster_Call {
	return &MockKCPHelper_NewClientForLogicalCluster_Call{Call: _e.mock.On("NewClientForLogicalCluster", ctx, cluster)}
}

func (_c *MockKCPHelper_NewClientForLogicalCluster_Call) Run(run func(ctx context.Context, cluster string)) *MockKCPHelper_NewClientForLogicalCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKCPHelper_NewClientForLogicalCluster_Call) Return(client1 client.Client, err error) *MockKCPHelper_NewClientForLogicalCluster_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *MockKCPHelper_NewClientForLogicalCluster_Call) RunAndReturn(run func(ctx context.Context, cluster string) (client.Client, error)) *MockKCPHelper_NewClientForLogicalCluster_Call {
	_c.Call.Return(run)
	return _c
}
