// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// MockKCPHelper is a backward-compatible alias for tests that still
// reference the old helper mock name.
type MockKCPHelper = MockKCPCombinedClientGetter

// NewMockKCPHelper creates a backward-compatible combined getter mock.
func NewMockKCPHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKCPHelper {
	return NewMockKCPCombinedClientGetter(t)
}

// NewMockKCPClientGetter creates a new instance of MockKCPClientGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKCPClientGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKCPClientGetter {
	mock := &MockKCPClientGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKCPClientGetter is an autogenerated mock type for the KCPClientGetter type
type MockKCPClientGetter struct {
	mock.Mock
}

type MockKCPClientGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKCPClientGetter) EXPECT() *MockKCPClientGetter_Expecter {
	return &MockKCPClientGetter_Expecter{mock: &_m.Mock}
}

// NewClientForLogicalCluster provides a mock function for the type MockKCPClientGetter
func (_mock *MockKCPClientGetter) NewClientForLogicalCluster(ctx context.Context, cluster string) (client.Client, error) {
	ret := _mock.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for NewClientForLogicalCluster")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Client, error)); ok {
		return returnFunc(ctx, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Client); ok {
		r0 = returnFunc(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKCPClientGetter_NewClientForLogicalCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClientForLogicalCluster'
type MockKCPClientGetter_NewClientForLogicalCluster_Call struct {
	*mock.Call
}

// NewClientForLogicalCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster string
func (_e *MockKCPClientGetter_Expecter) NewClientForLogicalCluster(ctx interface{}, cluster interface{}) *MockKCPClientGetter_NewClientForLogicalCluster_Call {
	return &MockKCPClientGetter_NewClientForLogicalCluster_Call{Call: _e.mock.On("NewClientForLogicalCluster", ctx, cluster)}
}

func (_c *MockKCPClientGetter_NewClientForLogicalCluster_Call) Run(run func(ctx context.Context, cluster string)) *MockKCPClientGetter_NewClientForLogicalCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKCPClientGetter_NewClientForLogicalCluster_Call) Return(client1 client.Client, err error) *MockKCPClientGetter_NewClientForLogicalCluster_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *MockKCPClientGetter_NewClientForLogicalCluster_Call) RunAndReturn(run func(ctx context.Context, cluster string) (client.Client, error)) *MockKCPClientGetter_NewClientForLogicalCluster_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKCPCombinedClientGetter creates a new instance of MockKCPCombinedClientGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKCPCombinedClientGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKCPCombinedClientGetter {
	mock := &MockKCPCombinedClientGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKCPCombinedClientGetter is an autogenerated mock type for the KCPCombinedClientGetter type
type MockKCPCombinedClientGetter struct {
	mock.Mock
}

type MockKCPCombinedClientGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKCPCombinedClientGetter) EXPECT() *MockKCPCombinedClientGetter_Expecter {
	return &MockKCPCombinedClientGetter_Expecter{mock: &_m.Mock}
}

// AllClient provides compatibility with the renamed interface method.
func (_mock *MockKCPCombinedClientGetter) AllClient(ctx context.Context, apiexportEndpointSliceName string) (client.Client, error) {
	return _mock.GetAllClient(ctx, apiexportEndpointSliceName)
}

// AllClient is a helper method to define mock.On call
//   - ctx context.Context
//   - apiexportEndpointSliceName string
func (_e *MockKCPCombinedClientGetter_Expecter) AllClient(ctx interface{}, apiexportEndpointSliceName interface{}) *MockKCPCombinedClientGetter_GetAllClient_Call {
	return _e.GetAllClient(ctx, apiexportEndpointSliceName)
}

// GetAllClient provides a mock function for the type MockKCPCombinedClientGetter
func (_mock *MockKCPCombinedClientGetter) GetAllClient(ctx context.Context, apiexportEndpointSliceName string) (client.Client, error) {
	ret := _mock.Called(ctx, apiexportEndpointSliceName)

	if len(ret) == 0 {
		panic("no return value specified for GetAllClient")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Client, error)); ok {
		return returnFunc(ctx, apiexportEndpointSliceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Client); ok {
		r0 = returnFunc(ctx, apiexportEndpointSliceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiexportEndpointSliceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKCPCombinedClientGetter_GetAllClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllClient'
type MockKCPCombinedClientGetter_GetAllClient_Call struct {
	*mock.Call
}

// GetAllClient is a helper method to define mock.On call
//   - ctx context.Context
//   - apiexportEndpointSliceName string
func (_e *MockKCPCombinedClientGetter_Expecter) GetAllClient(ctx interface{}, apiexportEndpointSliceName interface{}) *MockKCPCombinedClientGetter_GetAllClient_Call {
	return &MockKCPCombinedClientGetter_GetAllClient_Call{Call: _e.mock.On("GetAllClient", ctx, apiexportEndpointSliceName)}
}

func (_c *MockKCPCombinedClientGetter_GetAllClient_Call) Run(run func(ctx context.Context, apiexportEndpointSliceName string)) *MockKCPCombinedClientGetter_GetAllClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKCPCombinedClientGetter_GetAllClient_Call) Return(client1 client.Client, err error) *MockKCPCombinedClientGetter_GetAllClient_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *MockKCPCombinedClientGetter_GetAllClient_Call) RunAndReturn(run func(ctx context.Context, apiexportEndpointSliceName string) (client.Client, error)) *MockKCPCombinedClientGetter_GetAllClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientForLogicalCluster provides a mock function for the type MockKCPCombinedClientGetter
func (_mock *MockKCPCombinedClientGetter) NewClientForLogicalCluster(ctx context.Context, cluster string) (client.Client, error) {
	ret := _mock.Called(ctx, cluster)

	if len(ret) == 0 {
		panic("no return value specified for NewClientForLogicalCluster")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.Client, error)); ok {
		return returnFunc(ctx, cluster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.Client); ok {
		r0 = returnFunc(ctx, cluster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cluster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClientForLogicalCluster'
type MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call struct {
	*mock.Call
}

// NewClientForLogicalCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster string
func (_e *MockKCPCombinedClientGetter_Expecter) NewClientForLogicalCluster(ctx interface{}, cluster interface{}) *MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call {
	return &MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call{Call: _e.mock.On("NewClientForLogicalCluster", ctx, cluster)}
}

func (_c *MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call) Run(run func(ctx context.Context, cluster string)) *MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call) Return(client1 client.Client, err error) *MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call) RunAndReturn(run func(ctx context.Context, cluster string) (client.Client, error)) *MockKCPCombinedClientGetter_NewClientForLogicalCluster_Call {
	_c.Call.Return(run)
	return _c
}
