package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStoreIDGetter creates a new instance of MockStoreIDGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreIDGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreIDGetter {
	mock := &MockStoreIDGetter{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreIDGetter is an autogenerated mock type for the StoreIDGetter type
type MockStoreIDGetter struct {
	mock.Mock
}

type MockStoreIDGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreIDGetter) EXPECT() *MockStoreIDGetter_Expecter {
	return &MockStoreIDGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStoreIDGetter
func (_mock *MockStoreIDGetter) Get(ctx context.Context, storeName string) (string, error) {
	ret := _mock.Called(ctx, storeName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, storeName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoreIDGetter_Get_Call is a helper struct to make the mock expectations more readable
type MockStoreIDGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock expectations
func (_e *MockStoreIDGetter_Expecter) Get(ctx interface{}, storeName interface{}) *MockStoreIDGetter_Get_Call {
	return &MockStoreIDGetter_Get_Call{Call: _e.mock.On("Get", ctx, storeName)}
}

func (_c *MockStoreIDGetter_Get_Call) Run(run func(ctx context.Context, storeName string)) *MockStoreIDGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStoreIDGetter_Get_Call) Return(_a0 string, _a1 error) *MockStoreIDGetter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoreIDGetter_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockStoreIDGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}
