// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// MockAllPlatformMeshClient is an autogenerated mock type for the AllPlatformMeshClient type
type MockAllPlatformMeshClient struct {
	mock.Mock
}

type MockAllPlatformMeshClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAllPlatformMeshClient) EXPECT() *MockAllPlatformMeshClient_Expecter {
	return &MockAllPlatformMeshClient_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, list, opts
func (_m *MockAllPlatformMeshClient) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, list)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ObjectList, ...client.ListOption) error); ok {
		r0 = rf(ctx, list, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAllPlatformMeshClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAllPlatformMeshClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - list client.ObjectList
//   - opts ...client.ListOption
func (_e *MockAllPlatformMeshClient_Expecter) List(ctx interface{}, list interface{}, opts ...interface{}) *MockAllPlatformMeshClient_List_Call {
	return &MockAllPlatformMeshClient_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, list}, opts...)...)}
}

func (_c *MockAllPlatformMeshClient_List_Call) Run(run func(ctx context.Context, list client.ObjectList, opts ...client.ListOption)) *MockAllPlatformMeshClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.ListOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.ListOption)
			}
		}
		run(args[0].(context.Context), args[1].(client.ObjectList), variadicArgs...)
	})
	return _c
}

func (_c *MockAllPlatformMeshClient_List_Call) Return(_a0 error) *MockAllPlatformMeshClient_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAllPlatformMeshClient_List_Call) RunAndReturn(run func(context.Context, client.ObjectList, ...client.ListOption) error) *MockAllPlatformMeshClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAllPlatformMeshClient creates a new instance of MockAllPlatformMeshClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAllPlatformMeshClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAllPlatformMeshClient {
	mock := &MockAllPlatformMeshClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
