package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/kcp-dev/logicalcluster/v3"
)

// NewMockKcpHelper creates a new instance of MockKcpHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKcpHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKcpHelper {
	mock := &MockKcpHelper{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKcpHelper is an autogenerated mock type for the KcpClientHelper type
type MockKcpHelper struct {
	mock.Mock
}

type MockKcpHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKcpHelper) EXPECT() *MockKcpHelper_Expecter {
	return &MockKcpHelper_Expecter{mock: &_m.Mock}
}

// NewClientForLogicalCluster provides a mock function for the type MockKcpHelper
func (_mock *MockKcpHelper) NewClientForLogicalCluster(clusterKey logicalcluster.Name) (client.Client, error) {
	ret := _mock.Called(clusterKey)

	var r0 client.Client
	if rf, ok := ret.Get(0).(func(logicalcluster.Name) client.Client); ok {
		r0 = rf(clusterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(logicalcluster.Name) error); ok {
		r1 = rf(clusterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKcpHelper_NewClientForLogicalCluster_Call is a helper struct to make the mock expectations more readable
type MockKcpHelper_NewClientForLogicalCluster_Call struct {
	*mock.Call
}

// NewClientForLogicalCluster is a helper method to define mock expectations
func (_e *MockKcpHelper_Expecter) NewClientForLogicalCluster(clusterKey interface{}) *MockKcpHelper_NewClientForLogicalCluster_Call {
	return &MockKcpHelper_NewClientForLogicalCluster_Call{Call: _e.mock.On("NewClientForLogicalCluster", clusterKey)}
}

func (_c *MockKcpHelper_NewClientForLogicalCluster_Call) Run(run func(clusterKey logicalcluster.Name)) *MockKcpHelper_NewClientForLogicalCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(logicalcluster.Name))
	})
	return _c
}

func (_c *MockKcpHelper_NewClientForLogicalCluster_Call) Return(_a0 client.Client, _a1 error) *MockKcpHelper_NewClientForLogicalCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKcpHelper_NewClientForLogicalCluster_Call) RunAndReturn(run func(logicalcluster.Name) (client.Client, error)) *MockKcpHelper_NewClientForLogicalCluster_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockKcpHelper
func (_mock *MockKcpHelper) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, list)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.ObjectList, ...client.ListOption) error); ok {
		r0 = rf(ctx, list, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKcpHelper_List_Call is a helper struct to make the mock expectations more readable
type MockKcpHelper_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock expectations
func (_e *MockKcpHelper_Expecter) List(ctx interface{}, list interface{}, opts ...interface{}) *MockKcpHelper_List_Call {
	return &MockKcpHelper_List_Call{Call: _e.mock.On("List", append([]interface{}{ctx, list}, opts...)...)}
}

func (_c *MockKcpHelper_List_Call) Run(run func(ctx context.Context, list client.ObjectList, opts ...client.ListOption)) *MockKcpHelper_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]client.ListOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.ListOption)
			}
		}
		run(args[0].(context.Context), args[1].(client.ObjectList), variadicArgs...)
	})
	return _c
}

func (_c *MockKcpHelper_List_Call) Return(_a0 error) *MockKcpHelper_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKcpHelper_List_Call) RunAndReturn(run func(context.Context, client.ObjectList, ...client.ListOption) error) *MockKcpHelper_List_Call {
	_c.Call.Return(run)
	return _c
}
