// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenRefresher creates a new instance of MockTokenRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRefresher {
	mock := &MockTokenRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRefresher is an autogenerated mock type for the TokenRefresher type
type MockTokenRefresher struct {
	mock.Mock
}

type MockTokenRefresher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRefresher) EXPECT() *MockTokenRefresher_Expecter {
	return &MockTokenRefresher_Expecter{mock: &_m.Mock}
}

// RefreshToken provides a mock function for the type MockTokenRefresher
func (_mock *MockTokenRefresher) RefreshToken(ctx context.Context, clientID string) (string, error) {
	_va := []interface{}{ctx, clientID}
	_ca := make([]interface{}, len(_va))
	copy(_ca, _va)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRefresher_RefreshToken_Call is a *mock.Call that shadows *mock.Call with type safe methods.
type MockTokenRefresher_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockTokenRefresher_Expecter) RefreshToken(ctx interface{}, clientID interface{}) *MockTokenRefresher_RefreshToken_Call {
	return &MockTokenRefresher_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, clientID)}
}

func (_c *MockTokenRefresher_RefreshToken_Call) Run(run func(ctx context.Context, clientID string)) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRefresher_RefreshToken_Call) Return(newToken string, err error) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Return(newToken, err)
	return _c
}

func (_c *MockTokenRefresher_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
