# permissions for end users to edit authorizationmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fga-operator
    app.kubernetes.io/managed-by: kustomize
  name: authorizationmodel-editor-role
rules:
- apiGroups:
  - core.openmfp.io
  resources:
  - authorizationmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openmfp.io
  resources:
  - authorizationmodels/status
  verbs:
  - get
