# This rule is not used by the project security-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to core.platform-mesh.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: security-operator
    app.kubernetes.io/managed-by: kustomize
  name: invite-viewer-role
rules:
- apiGroups:
  - core.platform-mesh.io
  resources:
  - invites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - invites/status
  verbs:
  - get
