# permissions for end users to edit stores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fga-operator
    app.kubernetes.io/managed-by: kustomize
  name: store-editor-role
rules:
- apiGroups:
  - core.openmfp.io
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.openmfp.io
  resources:
  - stores/status
  verbs:
  - get
