# permissions for end users to view stores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: security-operator
    app.kubernetes.io/managed-by: kustomize
  name: store-viewer-role
rules:
- apiGroups:
  - core.platform-mesh.io
  resources:
  - stores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - stores/status
  verbs:
  - get
