apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: authorization.platform-mesh.io
spec:
  resources:
  - group: authorization.platform-mesh.io
    name: apiexportpolicies
    schema: v260310-c5ff50b.apiexportpolicies.authorization.platform-mesh.io
    storage:
      crd: {}
status: {}
