apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.platform-mesh.io
spec:
  latestResourceSchemas:
  - v250401-5769f6b.authorizationmodels.core.platform-mesh.io
  - v250401-66f7f53.stores.core.platform-mesh.io
status: {}
