//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/platform-mesh/security-operator/api/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModel) DeepCopyInto(out *AuthorizationModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModel.
func (in *AuthorizationModel) DeepCopy() *AuthorizationModel {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelList) DeepCopyInto(out *AuthorizationModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizationModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelList.
func (in *AuthorizationModelList) DeepCopy() *AuthorizationModelList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelSpec) DeepCopyInto(out *AuthorizationModelSpec) {
	*out = *in
	out.StoreRef = in.StoreRef
	if in.Tuples != nil {
		in, out := &in.Tuples, &out.Tuples
		*out = make([]v1alpha1.Tuple, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelSpec.
func (in *AuthorizationModelSpec) DeepCopy() *AuthorizationModelSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelStatus) DeepCopyInto(out *AuthorizationModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedTuples != nil {
		in, out := &in.ManagedTuples, &out.ManagedTuples
		*out = make([]v1alpha1.Tuple, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelStatus.
func (in *AuthorizationModelStatus) DeepCopy() *AuthorizationModelStatus {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceStoreRef) DeepCopyInto(out *WorkspaceStoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceStoreRef.
func (in *WorkspaceStoreRef) DeepCopy() *WorkspaceStoreRef {
	if in == nil {
		return nil
	}
	out := new(WorkspaceStoreRef)
	in.DeepCopyInto(out)
	return out
}
