name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: platform-mesh/.github/.github/workflows/pipeline-golang-app.yml@07550bab80de7691f4947214ee342351896e209b # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/platform-mesh/security-operator
      useTask: true
      useLocalCoverageConfig: true
      coverageThresholdTotal: 90