name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-app.yml@main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/fga-operator
      useTask: true
      useLocalCoverageConfig: true
      coverageThresholdTotal: 90