name: release

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    uses: platform-mesh/.github/.github/workflows/job-golang-lint.yml@116dcb7522b4cd1ba7fd2d969e8b6c556d1ec3bd # main
    with:
      useTask: true

  test:
    uses: platform-mesh/.github/.github/workflows/job-golang-test-source.yml@116dcb7522b4cd1ba7fd2d969e8b6c556d1ec3bd # main
    secrets: inherit
    with:
      useTask: true
      useLocalCoverageConfig: true

  create-version:
    uses: platform-mesh/.github/.github/workflows/job-create-version.yml@116dcb7522b4cd1ba7fd2d969e8b6c556d1ec3bd # main
    secrets: inherit
    permissions:
      contents: write

  docker-build-push:
    needs: [create-version, lint, test]
    uses: platform-mesh/.github/.github/workflows/job-docker-build-push.yml@116dcb7522b4cd1ba7fd2d969e8b6c556d1ec3bd # main
    secrets: inherit
    permissions:
      contents: write
      packages: write
      id-token: write
    with:
      imageTagName: ghcr.io/platform-mesh/security-operator
      version: ${{ needs.create-version.outputs.version }}
      multiarch: true

  update-version:
    needs: [create-version, docker-build-push]
    uses: platform-mesh/.github/.github/workflows/job-chart-version-update.yml@116dcb7522b4cd1ba7fd2d969e8b6c556d1ec3bd # main
    secrets: inherit
    with:
      appVersion: ${{ needs.create-version.outputs.version }}
      chart: security-operator
      targetRepository: platform-mesh/helm-charts

  sbom:
    needs: [create-version, docker-build-push]
    uses: platform-mesh/.github/.github/workflows/job-sbom.yml@116dcb7522b4cd1ba7fd2d969e8b6c556d1ec3bd # main
    permissions:
      contents: read
      packages: read
    with:
      imageReference: ghcr.io/platform-mesh/security-operator:${{ needs.create-version.outputs.version }}

  image-ocm:
    needs: [create-version, docker-build-push, sbom]
    uses: platform-mesh/.github/.github/workflows/job-image-ocm.yml@116dcb7522b4cd1ba7fd2d969e8b6c556d1ec3bd # main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      imageReference: ghcr.io/platform-mesh/security-operator:${{ needs.create-version.outputs.version }}
      appVersion: ${{ needs.create-version.outputs.version }}
      repoName: security-operator
      commit: ${{ github.sha }}
