//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicy) DeepCopyInto(out *APIExportPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicy.
func (in *APIExportPolicy) DeepCopy() *APIExportPolicy {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIExportPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicyList) DeepCopyInto(out *APIExportPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIExportPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicyList.
func (in *APIExportPolicyList) DeepCopy() *APIExportPolicyList {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIExportPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicySpec) DeepCopyInto(out *APIExportPolicySpec) {
	*out = *in
	out.APIExportRef = in.APIExportRef
	if in.AllowPathExpressions != nil {
		in, out := &in.AllowPathExpressions, &out.AllowPathExpressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicySpec.
func (in *APIExportPolicySpec) DeepCopy() *APIExportPolicySpec {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportPolicyStatus) DeepCopyInto(out *APIExportPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedAllowExpressions != nil {
		in, out := &in.ManagedAllowExpressions, &out.ManagedAllowExpressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportPolicyStatus.
func (in *APIExportPolicyStatus) DeepCopy() *APIExportPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(APIExportPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportRef) DeepCopyInto(out *APIExportRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportRef.
func (in *APIExportRef) DeepCopy() *APIExportRef {
	if in == nil {
		return nil
	}
	out := new(APIExportRef)
	in.DeepCopyInto(out)
	return out
}
